@BASE_URL = http://127.0.0.1:8000/v1/
@CONTENT_TYPE = application/json
@TOKEN = Token fd7b6866b362f97be80f5ea5fd4002cde2def401

# @name user_onboarding
POST  {{ BASE_URL }}user/ HTTP/1.1
Content-Type: {{ CONTENT_TYPE }}
Authorization: {{ TOKEN }}

{
 "first_name": "test_backend",
 "email": "mahe@vgts.com",
 "date_of_joining": "2010-07-30T15:05:00.000Z",
 "is_superuser": false,
 "phone": "7868122679",
 "user_role": 2,
 "employee_role": [2,3],
 "aadhaar_number": "84984922112141",
 "pan_number": "AZ6522111e1o3",
 "date_of_resignation": null,
 "reason_of_resignation": null,
 "salary_update_date": "2010-07-30T15:05:00.000Z"
}

###

# @name user_onboarding
PUT  {{ BASE_URL }}branch_incentive_update/18/ HTTP/1.1
Content-Type: {{ CONTENT_TYPE }}
Authorization: {{ TOKEN }}

[{
"id": 1,
"incentive": 100
},
{
"id": 2,
"incentive": 100
},
{
"id": 3,
"incentive": 100
}]
###

# @name product_onboarding
POST {{ BASE_URL }}product_create/ HTTP/1.1
Content-Type: {{ CONTENT_TYPE }}
Authorization: {{ TOKEN }}

{
  "name": "test_product",
  "unit": 1,
  "department": 1,
  "classification": 1,
  "reorder_level": 10,
  "sort_order": 4
}

###
# @name user_onboarding
GET  {{ BASE_URL }}attendance_user_list/17/2021-02-02/ HTTP/1.1
Content-Type: {{ CONTENT_TYPE }}
Authorization: {{ TOKEN }}


###

# @name user_onboarding
POST  {{ BASE_URL }}attendance_bulk_create/ HTTP/1.1
Content-Type: {{ CONTENT_TYPE }}

[
  {
    "id": 3,
    "key": 3,
    "username": "nanda",
    "email": "nanda@vishgyana.com",
    "first_name": "nanda",
    "last_name": "kumar",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "09786543210",
    "store": "guna",
    "aadhaar_number": null,
    "pan_number": null,
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": false,
    "check_out": true,
    "break_in": true,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      }
    ],
    "user_attendance": [
      {
        "id": "08bcfa2-223c-67a4-34d8-ac2c7eb0dfb",
        "existing": false,
        "start": "2021-01-30 15:40:53",
        "stop": "2021-01-30 16:35:38",
        "date": "2021-01-30"
      },
      {
        "id": "377b4fe-6057-2461-16a3-67be81d86c16",
        "existing": false,
        "start": "2021-01-30 16:35:43",
        "stop": null,
        "date": "2021-01-30"
      }
    ],
    "break_time": [
      {
        "id": "4faaf5-c31-c246-1c1e-ca681e182e1c",
        "existing": false,
        "start": "2021-01-30 16:22:47",
        "stop": "2021-01-30 16:35:38",
        "date": "2021-01-30"
      }
    ],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 5,
    "key": 5,
    "username": "Sujith",
    "email": "sujith1396@gmail.com",
    "first_name": "Sujith",
    "last_name": "Sujith",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "9866933955",
    "store": "guna",
    "aadhaar_number": null,
    "pan_number": null,
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [
      {
        "id": 130,
        "existing": true,
        "start": "2021-01-30 09:09:53",
        "stop": "2021-01-30 09:09:38",
        "date": "2021-01-30"
      },
      {
        "id": 129,
        "existing": true,
        "start": "2021-01-30 10:10:43",
        "stop": null,
        "date": "2021-01-30"
      }
    ],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 50,
    "key": 50,
    "username": "sujith",
    "email": "vigneshweran@vgts.com",
    "first_name": "sujith",
    "last_name": "",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "99988111714",
    "store": "guna",
    "aadhaar_number": "8498491124971",
    "pan_number": "AZ6511e11o3",
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      },
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 37,
    "key": 37,
    "username": "Sooraj Mehta",
    "email": "vigneshweran@vgts.com",
    "first_name": "Sooraj Mehta",
    "last_name": "",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "99988177714",
    "store": "guna",
    "aadhaar_number": "84984934931",
    "pan_number": "AZ6511e3",
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      },
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 27,
    "key": 27,
    "username": "vignesh",
    "email": "vicky@gmail.com",
    "first_name": "vignesh",
    "last_name": "eswaran",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "09998887776",
    "store": "guna",
    "aadhaar_number": "86438463846",
    "pan_number": "AZX3354",
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 39,
    "key": 39,
    "username": "sujith",
    "email": "vigneshweran@vgts.com",
    "first_name": "sujith",
    "last_name": "",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "99988175714",
    "store": "guna",
    "aadhaar_number": "84984924971",
    "pan_number": "AZ6511eo3",
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      },
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 40,
    "key": 40,
    "username": "sujith",
    "email": "vigneshweran@vgts.com",
    "first_name": "sujith",
    "last_name": "",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "99988171714",
    "store": "guna",
    "aadhaar_number": "849849124971",
    "pan_number": "AZ6511e1o3",
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      },
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 34,
    "key": 34,
    "username": "Vigneshwerann",
    "email": "vigneshweran@vgts.com",
    "first_name": "Vigneshwerann",
    "last_name": "",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "9998887774",
    "store": "guna",
    "aadhaar_number": "849849384931",
    "pan_number": "AZ6513",
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      },
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 35,
    "key": 35,
    "username": "Vigneshwerann",
    "email": "vigneshweran@vgts.com",
    "first_name": "Vigneshwerann",
    "last_name": "",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "99988877714",
    "store": "guna",
    "aadhaar_number": "8498493814931",
    "pan_number": "AZ65113",
    "date_of_resignation": null,
    "reason_of_resignation": null,
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      },
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  },
  {
    "id": 30,
    "key": 30,
    "username": "Vicky",
    "email": "vigneshweran@vgts.com",
    "first_name": "Vicky",
    "last_name": "",
    "date_of_joining": "2010-07-30T15:05:00",
    "phone": "9998887771",
    "store": "guna",
    "aadhaar_number": "849849384934",
    "pan_number": "AZ653",
    "date_of_resignation": "2021-01-30T07:41:03.551000",
    "reason_of_resignation": "This user is resignated",
    "check_in": true,
    "check_out": false,
    "break_in": false,
    "break_out": false,
    "role": [
      {
        "id": 1,
        "name": "Incharge",
        "code": 1,
        "description": "abcd",
        "status": true,
        "updated": "2021-01-24T13:37:14.618636",
        "created": "2021-01-19T15:32:34.394143"
      },
      {
        "id": 2,
        "name": "Tea master",
        "code": 2,
        "description": "abc",
        "status": false,
        "updated": "2021-01-24T13:37:17.769813",
        "created": "2021-01-19T15:44:47.396163"
      }
    ],
    "user_attendance": [],
    "break_time": [],
    "update": false,
    "delete": false,
    "new": false
  }
]


###
# @name sub_branch_create
PUT  {{ BASE_URL }}sub_branch_create/2/ HTTP/1.1
Content-Type: {{ CONTENT_TYPE }}

{
  "name": "sbranch"
}












# @BASE_URL = http://southindiancoffee.vgts.tech/v1/
# @CONTENT_TYPE = application/json
# @TOKEN = qwddc

# # @name store_specific_user

# POST  {{ BASE_URL }}store_specific_user/1/ HTTP/1.1
# Content-Type: {{ CONTENT_TYPE }}

# {
# "username": "Vigneshwerann",
# "email": "vigneshweran@vgts.com",
# "date_of_joining": "2010-07-30T15:05:00.000Z",
# "store": 1,
# "is_superuser": false,
# "phone": "9998887771",
# "is_staff": false,
# "is_employee": true,
# "is_admin": false,
# "employee_role": [1,2],
# "aadhaar_number": "849849384934",
# "pan_number": "AZ653",
# "per_hour": 62.5,
# "work_hours": 8,
# "ot_per_hour": 30,
# "date_of_resignation": null,
# "reason_of_resignation": null,
# "salary_update_date": "2010-07-30T15:05:00.000Z",
# "per_hour": 60,
# "work_hour": 8,
# "ot_per_hour":30
# }

