@BASE_URL = http://southindiancoffee.vgts.tech/v1/
@CONTENT_TYPE = application/json
@TOKEN = qwddc

# @name user_onboarding
POST  {{ BASE_URL }}user/ HTTP/1.1
Content-Type: {{ CONTENT_TYPE }}

{
"username": "nesamaniiii",
"first_name": "nesamani",
"last_name": "n",
"password1": "test@123",
"password2": "test@123",
"email": "nesamani@vgts.com",
"date_of_joining": "2010-07-30T15:05:00.000Z",
"store": 1,
"is_superuser": false,
"phone": "87654333320",
"is_staff": false,
"is_employee": true,
"is_admin": false,
"employee_role": [1,2]
}

# # @name user_onboarding
# POST  {{ BASE_URL }}user/ HTTP/1.1
# Content-Type: {{ CONTENT_TYPE }}

# {
# "username": "nesamanii",
# "first_name": "nesamani",
# "last_name": "n",
# "password1": "test@123",
# "password2": "test@123",
# "email": "nesamani@vgts.com",
# "date_of_joining": "2010-07-30T15:05:00.000Z",
# "store": 1,
# "is_superuser": false,
# "phone": "87654330620",
# "is_staff": false,
# "is_employee": true,
# "is_admin": false,
# "employee_role": [1,2]
# }