# Generated by Django 3.1.3 on 2021-01-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductcategory',
            name='store',
        ),
    ]
