# Generated by Django 3.1.3 on 2021-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_storeproductcategory_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricingbatch',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_batch',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_batch',
            field=models.ManyToManyField(to='core.ProductPricingBatch'),
        ),
        migrations.RemoveField(
            model_name='productstoremapping',
            name='product',
        ),
        migrations.AddField(
            model_name='productstoremapping',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
