# Generated by Django 3.1.3 on 2021-01-19 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_storeproductcategory_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricingbatch',
            name='date',
            field=models.DateTimeField(default='2012-09-04 06:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_batch',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_batch',
            field=models.ManyToManyField(to='core.ProductPricingBatch'),
        ),
        migrations.DeleteModel(
            name='ProductStoreMapping',
        ),
    ]
