# Generated by Django 3.1.3 on 2021-01-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210118_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoremapping',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
    ]
