# Generated by Django 3.1.3 on 2021-01-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210118_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstoremapping',
            name='store',
        ),
    ]
