# Generated by Django 3.1.3 on 2021-01-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_productstoremapping_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoremapping',
            name='store',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.store'),
            preserve_default=False,
        ),
    ]
