# Generated by Django 3.1.3 on 2021-01-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_freebillcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebill',
            name='billed_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.freebillcustomer'),
            preserve_default=False,
        ),
    ]
