# Generated by Django 3.1.3 on 2021-01-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_freebill_billed_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='store',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.CreateModel(
            name='StoreBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_branch', to='core.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
