# Generated by Django 3.1.3 on 2021-01-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210122_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='freebillcustomer',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gst',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storeproductcategory',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storeproducttype',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
