# Generated by Django 3.1.3 on 2021-01-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productstoremapping_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstoremapping',
            name='store',
        ),
    ]
