# Generated by Django 3.1.3 on 2021-01-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_productstoremapping_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoremapping',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
    ]
