# Generated by Django 3.1.3 on 2021-01-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210122_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Character field', max_length=200)),
                ('iso3', models.CharField(help_text='Character field', max_length=20)),
                ('iso2', models.CharField(help_text='Character field', max_length=20)),
                ('phone_code', models.CharField(help_text='Character field', max_length=50)),
                ('capital', models.CharField(help_text='Character field', max_length=200)),
                ('currency', models.CharField(help_text='Character field', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Character field', max_length=200)),
                ('state_code', models.CharField(help_text='Character field', max_length=50)),
                ('country', models.ForeignKey(help_text='Country foreign key', on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Character field', max_length=200)),
                ('latitude', models.CharField(help_text='Character field', max_length=30)),
                ('longitude', models.CharField(help_text='Character field', max_length=30)),
                ('state', models.ForeignKey(help_text='State foreign key', on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
