# Generated by Django 3.1.3 on 2021-01-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_city_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.ForeignKey(default=1, help_text='City foreign key', on_delete=django.db.models.deletion.CASCADE, related_name='city_stores', to='core.city'),
            preserve_default=False,
        ),
    ]
