# Generated by Django 3.1.3 on 2021-01-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_store_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='date_of_resignation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='reason_of_resignation',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
