# Generated by Django 3.1.3 on 2021-01-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210119_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStoreMapping',
        ),
    ]
