# Generated by Django 3.1.3 on 2021-01-25 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210125_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 12, 47, 51, 383816)),
            preserve_default=False,
        ),
    ]
