# Generated by Django 3.1.3 on 2021-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userattendancebreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='employee_role',
            field=models.ManyToManyField(blank=True, related_name='role_user', to='core.EmployeeRole'),
        ),
    ]
