# Generated by Django 3.1.3 on 2021-01-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210127_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsalecustomer',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_credit_sale_customer', to='core.store'),
            preserve_default=False,
        ),
    ]
