# Generated by Django 3.1.3 on 2021-01-27 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_creditsalecustomer_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 12, 26, 2, 411754)),
            preserve_default=False,
        ),
    ]
