# Generated by Django 3.1.3 on 2021-01-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_creditsales_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('opening_reading', models.CharField(db_index=True, max_length=100, unique=True)),
                ('closing_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_electric_bill', to='core.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
