# Generated by Django 3.1.3 on 2021-01-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210127_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbill',
            name='opening_reading',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
