# Generated by Django 3.1.3 on 2021-01-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210127_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricbill',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_electric_bill', to='core.branch'),
            preserve_default=False,
        ),
    ]
