# Generated by Django 3.1 on 2021-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210128_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freebillcustomer',
            name='code',
        ),
        migrations.AlterField(
            model_name='userattendancebreak',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
