# Generated by Django 3.1.3 on 2021-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210205_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
