# Generated by Django 3.1.3 on 2021-02-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210205_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBranchMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='StoreProductCategory',
            new_name='BranchProductClassification',
        ),
        migrations.RenameModel(
            old_name='StoreProductType',
            new_name='BranchProductDepartment',
        ),
        migrations.RemoveField(
            model_name='store',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='store',
            name='city',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='store',
        ),
        migrations.RemoveField(
            model_name='bulkorder',
            name='store',
        ),
        migrations.RemoveField(
            model_name='creditsalecustomer',
            name='store',
        ),
        migrations.RemoveField(
            model_name='creditsales',
            name='store',
        ),
        migrations.RemoveField(
            model_name='electricbill',
            name='store',
        ),
        migrations.RemoveField(
            model_name='freebill',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='productpricingbatch',
            name='store',
        ),
        migrations.RemoveField(
            model_name='wrongbill',
            name='store',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_users', to='core.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(default='chennai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(default=1, help_text='City foreign key', on_delete=django.db.models.deletion.CASCADE, related_name='city_branch', to='core.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(default=625002, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_bulk_order', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsalecustomer',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='branch_credit_sale_customer', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsales',
            name='branch',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='branch_credit_sale', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freebill',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='branch_free_bill', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_product', to='core.branchproductclassification'),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_product', to='core.branchproductdepartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinventory',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpricingbatch',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrongbill',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_wrong_bill', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electricbill',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_electric_bill', to='core.branch'),
        ),
        migrations.DeleteModel(
            name='ProductStoreMapping',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='productbranchmapping',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AddField(
            model_name='productbranchmapping',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.AddField(
            model_name='branch',
            name='sub_branch',
            field=models.ManyToManyField(blank=True, related_name='branch_sub_branch', to='core.SubBranch'),
        ),
        migrations.AddField(
            model_name='electricbill',
            name='sub_branch',
            field=models.ForeignKey(blank=True, default=8, on_delete=django.db.models.deletion.CASCADE, related_name='sub_branch_electric_bill', to='core.subbranch'),
            preserve_default=False,
        ),
    ]
