# Generated by Django 3.1.3 on 2021-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_branchincentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
