# Generated by Django 3.1.3 on 2021-02-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210219_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchincentive',
            name='department',
        ),
        migrations.RemoveField(
            model_name='branchincentive',
            name='incentive',
        ),
    ]
