# Generated by Django 3.1.3 on 2021-02-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210219_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDepartmentIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_product_department_name', to='core.branchproductdepartment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchEmployeeIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_branch_name', to='core.branch')),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_employee_role_name', to='core.employeerole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BranchIncentive',
        ),
        migrations.AddField(
            model_name='branchdepartmentincentive',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branchemployeeincentive'),
        ),
    ]
