# Generated by Django 3.1.3 on 2021-02-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210219_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchdepartmentincentive',
            old_name='employee',
            new_name='role',
        ),
    ]
