# Generated by Django 3.1.3 on 2021-02-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210219_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdepartmentincentive',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_branch_department_role', to='core.branchemployeeincentive'),
        ),
    ]
