# Generated by Django 3.1 on 2021-02-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210219_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlickposProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slickpos_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category_id', models.CharField(max_length=100)),
                ('taxgroup_id', models.CharField(max_length=100)),
                ('marked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('register_id', models.CharField(blank=True, max_length=100, null=True)),
                ('variant_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('addon_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
