# Generated by Django 3.1.3 on 2021-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_slickposproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slickposproducts',
            name='slickpos_id',
            field=models.CharField(max_length=100),
        ),
    ]
