# Generated by Django 3.1.3 on 2021-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210222_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='address1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
