# Generated by Django 3.1.3 on 2021-02-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210224_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='date_of_birth',
        ),
    ]
