# Generated by Django 3.1.3 on 2021-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_baseuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
