# Generated by Django 3.1.3 on 2021-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_usersalary_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
