# Generated by Django 3.1.3 on 2021-03-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_usersalaryperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalaryperday',
            name='time_spend',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
