# Generated by Django 3.1.3 on 2021-03-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20210304_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalaryperday',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
