# Generated by Django 3.1.3 on 2021-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_usersalaryperday_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersalaryperday',
            name='present',
        ),
        migrations.AddField(
            model_name='usersalaryperday',
            name='attendance',
            field=models.IntegerField(choices=[(1, 'Absent'), (2, 'Present'), (3, 'Present For Half Day')], default=2),
            preserve_default=False,
        ),
    ]
