# Generated by Django 3.1.3 on 2021-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20210304_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalaryperday',
            name='ot_time_spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
