# Generated by Django 3.1.3 on 2021-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_usersalaryperday_ot_time_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
