# Generated by Django 3.1.3 on 2021-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20210304_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='stop',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
