# Generated by Django 3.1.3 on 2021-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20210305_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendancebreak',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userattendancebreak',
            name='stop',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
