# Generated by Django 3.1.3 on 2021-03-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20210308_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='sell',
            new_name='taken',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_batch',
        ),
        migrations.RemoveField(
            model_name='productpricingbatch',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_product', to='core.branchproductdepartment'),
        ),
        migrations.AlterField(
            model_name='productpricingbatch',
            name='Buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productpricingbatch',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='InventoryControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('opening_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('closing_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('received_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
