# Generated by Django 3.1.3 on 2021-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20210309_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='date',
        ),
        migrations.AddField(
            model_name='productpricingbatch',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='on_hand',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='received',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='taken',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
