# Generated by Django 3.1.3 on 2021-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20210309_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OilConcumption',
            new_name='OilConsumption',
        ),
        migrations.AddField(
            model_name='productpricingbatch',
            name='product_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorycontrol',
            name='closing_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventorycontrol',
            name='opening_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventorycontrol',
            name='received_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
