# Generated by Django 3.1.3 on 2021-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20210310_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwastage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodwastage',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
