# Generated by Django 3.1.3 on 2021-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20210310_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycontrol',
            name='received_stock',
        ),
    ]
