# Generated by Django 3.1.3 on 2021-03-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_inventorycontrol_received_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricingbatch',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_batch', to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='electricbill',
            name='sub_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_branch_electric_bill', to='core.subbranch'),
        ),
        migrations.AlterField(
            model_name='inventorycontrol',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventory_control', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='inventorycontrol',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory_control', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventory', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productpricingbatch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_batch', to='core.branch'),
        ),
    ]
