# Generated by Django 3.1.3 on 2021-03-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20210311_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OilConsumption',
        ),
        migrations.AlterField(
            model_name='electricbill',
            name='unit',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='unit_EB', to='core.unit'),
            preserve_default=False,
        ),
    ]
