# Generated by Django 3.1.3 on 2021-03-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20210311_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.IntegerField(choices=[(1, 'Friyer'), (2, 'Kadai')])),
                ('fresh_oil', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('used_oil', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('wastage_oil', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_oil_consumption', to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
