# Generated by Django 3.1.3 on 2021-03-11 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_oilconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilconsumption',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 17, 46, 21, 491224)),
            preserve_default=False,
        ),
    ]
