# Generated by Django 3.1.3 on 2021-03-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_oilconsumption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodwastage',
            name='sub_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_branch_food_wastage', to='core.subbranch'),
        ),
    ]
