# Generated by Django 3.1.3 on 2021-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_foodwastage_sub_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodwastage',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ElectricBill',
        ),
    ]
