# Generated by Django 3.1.3 on 2021-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_ebmeter_electricbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycontrol',
            name='on_hand',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
