# Generated by Django 3.1.3 on 2021-03-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_inventorycontrol_on_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilconsumption',
            name='unit',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='unit_oliconsumption', to='core.unit'),
            preserve_default=False,
        ),
    ]
