# Generated by Django 3.1.3 on 2021-03-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_oilconsumption_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freebill',
            name='billed_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.freebillcustomer'),
        ),
    ]
