# Generated by Django 3.1.3 on 2021-03-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20210312_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricbill',
            old_name='eb_meter',
            new_name='meter',
        ),
    ]
