# Generated by Django 3.1 on 2021-03-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20210315_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone2',
        ),
    ]
