# Generated by Django 3.1 on 2021-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20210315_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Bank')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, default=9876543210, max_length=20),
            preserve_default=False,
        ),
    ]
