# Generated by Django 3.1 on 2021-03-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20210315_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditsalecustomer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='creditsalecustomer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='creditsalecustomer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='creditsalecustomer',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='creditsalecustomer',
            name='phone2',
        ),
    ]
