# Generated by Django 3.1 on 2021-03-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20210315_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='creditsalecustomer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditsalecustomer',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsalecustomer',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Bank')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditsalecustomer',
            name='phone',
            field=models.CharField(db_index=True, default=45225, max_length=20),
            preserve_default=False,
        ),
    ]
