# Generated by Django 3.1 on 2021-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20210315_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone1',
            field=models.CharField(db_index=True, default=4343, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
