# Generated by Django 3.1 on 2021-03-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_pettycash_pettycashremark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricbill',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='electricbill',
            name='unit',
        ),
        migrations.DeleteModel(
            name='EBMeter',
        ),
        migrations.DeleteModel(
            name='ElectricBill',
        ),
    ]
