# Generated by Django 3.1 on 2021-03-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_bankcashreceiveddetails_denomination_storecashmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCashManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('opening_cash', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('closing_cash', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('expenses', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('incentive', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sky_cash', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('credit_sales', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bank_cash', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_sales', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_cash_management', to='core.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StoreCashManagement',
        ),
        migrations.AddField(
            model_name='bankcashreceiveddetails',
            name='branch',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='branch_bank_receive_details', to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denomination',
            name='branch',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='branch_denomination', to='core.branch'),
            preserve_default=False,
        ),
    ]
