# Generated by Django 3.1 on 2021-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20210316_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
