# Generated by Django 3.1 on 2021-03-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_pettycashremark_petty_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycashremark',
            name='petty_cash',
        ),
    ]
