# Generated by Django 3.1 on 2021-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_remove_pettycashremark_petty_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycontrol',
            name='usage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
