# Generated by Django 3.1 on 2021-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_inventorycontrol_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbranchmapping',
            name='product',
            field=models.ManyToManyField(related_name='branch', to='core.Product'),
        ),
    ]
