# Generated by Django 3.1 on 2021-03-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20210319_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricbill',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='electricbill',
            name='unit',
        ),
        migrations.DeleteModel(
            name='EBMeter',
        ),
        migrations.DeleteModel(
            name='ElectricBill',
        ),
    ]
