# Generated by Django 3.1.7 on 2021-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_ebmeter_electricbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpricingbatch',
            old_name='Buying_price',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='productpricingbatch',
            name='product_unique_id',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
