# Generated by Django 3.1.7 on 2021-03-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20210323_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpricingbatch',
            old_name='rate',
            new_name='buying_price',
        ),
    ]
