# Generated by Django 3.1.7 on 2021-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20210323_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
