# Generated by Django 3.1.7 on 2021-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_productinventory_mrp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freebill',
            name='bill_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wrongbill',
            name='bill_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
