# Generated by Django 3.1.7 on 2021-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongbill',
            name='correct_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wrongbill',
            name='wrong_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
