# Generated by Django 3.1.2 on 2020-10-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('per_hour', models.PositiveIntegerField()),
                ('per_minute', models.PositiveIntegerField()),
                ('work_hours', models.PositiveIntegerField()),
                ('ot_per_hour', models.PositiveIntegerField()),
                ('ot_per_minute', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
