# Generated by Django 3.1.2 on 2020-10-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_usersalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_salaries', to='core_app.baseuser'),
            preserve_default=False,
        ),
    ]
