# Generated by Django 3.1.2 on 2020-10-14 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_usersalary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_of_joining',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
