# Generated by Django 3.1.2 on 2020-11-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_auto_20201102_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='store',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='core_app.store'),
            preserve_default=False,
        ),
    ]
