# Generated by Django 3.1.3 on 2020-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_auto_20201130_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='ot_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
