# Generated by Django 3.1 on 2020-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_auto_20201201_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='recipe_item',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='recipe_item',
            field=models.ManyToManyField(to='core_app.ProductRecipeItem'),
        ),
    ]
