# Generated by Django 3.1.3 on 2020-12-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_auto_20201205_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='branch',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='core_app.store'),
        ),
    ]
