# Generated by Django 3.1.3 on 2020-12-07 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_auto_20201205_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 7, 11, 36, 52, 399968)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
