# Generated by Django 3.1.3 on 2020-12-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_auto_20201207_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='date_of_joining',
        ),
    ]
