# Generated by Django 3.1.3 on 2020-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_remove_baseuser_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_of_joining',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
