# Generated by Django 3.1.3 on 2020-12-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_baseuser_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_employee',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
