# Generated by Django 3.1.3 on 2020-12-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_baseuser_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebill',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_free_bill', to='core_app.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrongbill',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_wrong_bill', to='core_app.store'),
            preserve_default=False,
        ),
    ]
