# Generated by Django 3.1.3 on 2020-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_auto_20201208_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
