# Generated by Django 3.1.3 on 2021-01-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_auto_20201214_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='time_spend',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
