# Generated by Django 3.1.4 on 2021-01-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_auto_20210107_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='ot_time_spend',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
