# Generated by Django 3.1.3 on 2021-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_auto_20210107_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalary',
            name='ot_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='ot_per_minute',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='per_minute',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='work_minutes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
